### ISSUE TITLE
Adds extra white space on empty line

### ISSUE THREAD

**Issue by kdorsel** [Roald87/TcBlack#33]
Adds extra white space on empty line between variable declarations.

![image](https://user-images.githubusercontent.com/2569415/86045319-6c2c1b00-ba19-11ea-8b04-48c05fa86b67.png)

**Comment by Roald87** [comment]
Hi @kdorsel!

Thanks for your input. This is intended behavior, see #15. I implemented this because first the Visual Studio TwinCAT editor automatically adds these indents and second because then you are immediately at the right level if you want to add an extra variable.
