### ISSUE TITLE
GUI/Integration into Visual Studio for TcBlack

### ISSUE THREAD

**Issue by sagatowski** [Roald87/TcBlack#51]
Is it possible to add an GUI/Integration to Visual Studio for TcBlack, the same way that StWeep is integrated into Visual Studio? Would be nice to have an open-source alternative to StWeep.

**Comment by SankariNL** [comment]
I agree, this would be great. Depending on your setup and version control system you could run it directly from the IDE, or with the command line tool activated by GIT for example.

**Comment by Roald87** [comment]
Closing. Just released [a very rudimentary plugin](https://github.com/Roald87/TcBlack/releases/tag/TcBlackExtension_v0.1.0).

**Comment by sagatowski** [comment]
Really cool @Roald87 ! Will have to try this out!
